# Copyright 2026 The Vivisect Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

module(
    name = "vivisect",
    version = "0.1.0",
)

bazel_dep(name = "bazel_skylib", version = "1.8.2")
bazel_dep(name = "platforms", version = "1.0.0")
bazel_dep(name = "rules_cc", version = "0.2.17")
bazel_dep(name = "rules_python", version = "1.7.0")

# Explicit Vivado Toolchain Configuration
vivado = use_extension("//rules/toolchains:vivado.bzl", "vivado")
vivado.toolchain(
    name = "vivado_default",
    install_path = "/tools/Xilinx/2026.1/Vivado",
    version = "2026.1",
)
use_repo(vivado, "vivado_default")

register_toolchains("@vivado_default//:toolchain")

# Explicit Verilator Toolchain Configuration
verilator = use_extension("//rules/toolchains:verilator.bzl", "verilator")
verilator.toolchain(
    name = "verilator_default",
    include_dir = "/usr/share/verilator/include",
    path = "/usr/bin/verilator",
    version = "5.020",
)
use_repo(verilator, "verilator_default")

register_toolchains("@verilator_default//:toolchain")
