# Copyright 2026 The Vivisect Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("@rules_python//python:defs.bzl", "py_test")
load(":providers_test.bzl", "providers_test_suite")

providers_test_suite(name = "providers_test")

py_test(
    name = "utilization_runner_test",
    srcs = ["utilization_runner_test.py"],
)

py_test(
    name = "timing_runner_test",
    srcs = ["timing_runner_test.py"],
)

py_test(
    name = "style_test",
    srcs = ["style_test.py"],
    tags = ["local", "no-sandbox", "external"],
)

load("//rules:defs.bzl", "sv_library")
load(
    ":stage_transition_test.bzl",
    "sim_inspector",
    "sim_stage_test",
    "synth_inspector",
    "synth_stage_test",
    "verilator_inspector",
    "verilator_stage_test",
)

# Multi-stage library selecting source files based on target stage
sv_library(
    name = "stage_select_lib",
    srcs = select({
        "//rules:is_synthesis": ["synth_impl.sv"],
        "//rules:is_simulation": ["sim_impl.sv"],
        "//rules:is_verilator": ["verilator_impl.sv"],
    }),
)

synth_inspector(
    name = "synth_inspect",
    dep = ":stage_select_lib",
)

synth_stage_test(
    name = "synth_stage_test",
    target_under_test = ":synth_inspect",
)

sim_inspector(
    name = "sim_inspect",
    dep = ":stage_select_lib",
)

sim_stage_test(
    name = "sim_stage_test",
    target_under_test = ":sim_inspect",
)

verilator_inspector(
    name = "verilator_inspect",
    dep = ":stage_select_lib",
)

verilator_stage_test(
    name = "verilator_stage_test",
    target_under_test = ":verilator_inspect",
)
