# Copyright 2026 The Vivisect Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Verilator lint test rule running verilator --lint-only on SystemVerilog sources."""

load("//rules:providers.bzl", "SvInfo")
load("//rules:stage.bzl", "verilator_transition")

VERILATOR_TOOLCHAIN_TYPE = Label("//rules/toolchains:verilator_toolchain_type")

def _verilator_lint_test_impl(ctx):
    tc = ctx.toolchains[VERILATOR_TOOLCHAIN_TYPE].verilator

    dep_pkgs = []
    dep_interfaces = []
    dep_modules = []
    all_hdrs = []
    all_includes = []
    all_defines = []
    all_waivers = []

    for dep in ctx.attr.deps:
        if SvInfo in dep:
            info = dep[SvInfo]
            if hasattr(info, "pkgs") and info.pkgs:
                dep_pkgs.append(info.pkgs)
            if hasattr(info, "interfaces") and info.interfaces:
                dep_interfaces.append(info.interfaces)
            if hasattr(info, "modules") and info.modules:
                dep_modules.append(info.modules)
            elif hasattr(info, "transitive_srcs") and info.transitive_srcs:
                known_pkgs = {f.path: True for f in info.pkgs.to_list()} if hasattr(info, "pkgs") and info.pkgs else {}
                known_ifs = {f.path: True for f in info.interfaces.to_list()} if hasattr(info, "interfaces") and info.interfaces else {}
                fallback = [f for f in info.transitive_srcs.to_list() if f.path not in known_pkgs and f.path not in known_ifs]
                if fallback:
                    dep_modules.append(depset(fallback))
            all_hdrs.extend(info.hdrs.to_list())
            all_includes.extend(info.includes.to_list())
            all_defines.extend(info.defines.to_list())
            if hasattr(info, "waivers") and info.waivers:
                all_waivers.extend(info.waivers.to_list())

    # Add direct sources if given
    raw_srcs = ctx.files.srcs
    direct_srcs = [s for s in raw_srcs if not s.path.endswith(".vlt")]
    direct_src_waivers = [s for s in raw_srcs if s.path.endswith(".vlt")]

    all_waivers.extend(direct_src_waivers)
    all_waivers.extend(ctx.files.waivers)

    # Order sources strictly: packages -> interfaces -> modules -> direct sources
    ordered_pkgs = depset(order = "postorder", transitive = dep_pkgs).to_list()
    ordered_interfaces = depset(order = "postorder", transitive = dep_interfaces).to_list()
    ordered_modules = depset(order = "postorder", transitive = dep_modules).to_list()

    all_srcs = ordered_pkgs + ordered_interfaces + ordered_modules + direct_srcs

    # De-duplicate sources preserving order
    seen_srcs = {}
    dedup_srcs = []
    for s in all_srcs:
        if s.path not in seen_srcs:
            seen_srcs[s.path] = True
            dedup_srcs.append(s)

    # De-duplicate waivers preserving order
    seen_waivers = {}
    dedup_waivers = []
    for w in all_waivers:
        if w.path not in seen_waivers:
            seen_waivers[w.path] = True
            dedup_waivers.append(w)

    target_type = ctx.attr.target_type
    target_name = ctx.attr.top
    if not target_name:
        if ctx.attr.deps:
            target_name = ctx.attr.deps[0].label.name
        else:
            target_name = ctx.label.name

    stub_files = []
    top_module = ctx.attr.top
    extra_flags = []

    if target_type == "package":
        stub_top_module = "_vivisect_pkg_lint_top"
        stub_file = ctx.actions.declare_file(ctx.label.name + "_pkg_lint_top.sv")
        ctx.actions.write(
            output = stub_file,
            content = """// Synthetic lint stub generated by Vivisect verilator_lint_test
module %s;
  import %s::*;
endmodule
""" % (stub_top_module, target_name),
        )
        stub_files.append(stub_file)
        top_module = stub_top_module
        extra_flags.extend(["-Wno-UNUSEDPARAM", "-Wno-DECLFILENAME"])
    elif target_type == "interface":
        stub_top_module = "_vivisect_if_lint_top"
        stub_file = ctx.actions.declare_file(ctx.label.name + "_if_lint_top.sv")
        param_inst = ""
        if ctx.attr.parameters:
            param_assigns = [".%s(%s)" % (k, v) for k, v in ctx.attr.parameters.items()]
            param_inst = " #(\n    " + ",\n    ".join(param_assigns) + "\n  )"

        stub_content = """// Synthetic lint stub generated by Vivisect verilator_lint_test
module %s;
  %s%s _if_inst();
endmodule
""" % (stub_top_module, target_name, param_inst)
        ctx.actions.write(
            output = stub_file,
            content = stub_content,
        )
        stub_files.append(stub_file)
        top_module = stub_top_module
        extra_flags.extend([
            "-Wno-UNUSEDSIGNAL",
            "-Wno-UNDRIVEN",
            "-Wno-UNUSEDPARAM",
            "-Wno-PINMISSING",
            "-Wno-DECLFILENAME",
        ])
    elif target_type == "module":
        top_module = ctx.attr.top
    else:
        fail("Unsupported target_type '%s'. Allowed values: 'module', 'package', 'interface'." % target_type)

    script = ctx.actions.declare_file(ctx.label.name + ".sh")

    cmd_args = [tc.verilator_path, "--lint-only"]
    cmd_args.extend(ctx.attr.warning_flags)
    cmd_args.extend(ctx.attr.lint_flags)
    cmd_args.extend(extra_flags)

    if top_module:
        cmd_args.extend(["--top-module", top_module])

    for inc in all_includes:
        cmd_args.extend(["-I" + inc])

    for d in all_defines:
        cmd_args.extend(["-D" + d])

    for w in dedup_waivers:
        cmd_args.append(w.short_path)

    for s in dedup_srcs:
        cmd_args.append(s.short_path)

    for sf in stub_files:
        cmd_args.append(sf.short_path)

    # Generate test script
    script_content = """#!/usr/bin/env bash
set -euo pipefail

exec {cmd}
""".format(
        cmd = " ".join(["\"" + arg + "\"" for arg in cmd_args]),
    )

    ctx.actions.write(
        output = script,
        content = script_content,
        is_executable = True,
    )

    runfiles = ctx.runfiles(files = dedup_srcs + all_hdrs + dedup_waivers + stub_files)
    return [
        DefaultInfo(
            executable = script,
            runfiles = runfiles,
        ),
    ]

verilator_lint_test = rule(
    implementation = _verilator_lint_test_impl,
    test = True,
    doc = "Executes Verilator lint checks (--lint-only) across SystemVerilog dependencies.",
    attrs = {
        "deps": attr.label_list(
            providers = [SvInfo],
            default = [],
            doc = "SystemVerilog libraries to lint.",
            cfg = verilator_transition,
        ),
        "srcs": attr.label_list(
            allow_files = [".sv", ".v", ".vlt"],
            doc = "Optional direct source files.",
        ),
        "waivers": attr.label_list(
            allow_files = [".vlt"],
            default = [],
            doc = "Verilator .vlt configuration and waiver files.",
        ),
        "top": attr.string(
            default = "",
            doc = "Top-level module name to lint.",
        ),
        "target_type": attr.string(
            default = "module",
            values = ["module", "package", "interface"],
            doc = "Target type to lint: 'module', 'package', or 'interface'. Defaults to 'module'.",
        ),
        "parameters": attr.string_dict(
            default = {},
            doc = "Parameter overrides for synthetic interface or module stub.",
        ),
        "warning_flags": attr.string_list(
            default = ["-Wall"],
            doc = "Warning enablement flags (defaults to -Wall).",
        ),
        "lint_flags": attr.string_list(
            default = [],
            doc = "Additional Verilator flags (e.g. -Wno-UNUSEDSIGNAL).",
        ),
        "_allowlist_function_transition": attr.label(
            default = "@bazel_tools//tools/allowlists/function_transition_allowlist",
        ),
    },
    toolchains = [VERILATOR_TOOLCHAIN_TYPE],
)
